# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 9, 27, 4, 59, 55, 568878, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
