# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
