# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160517_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('name', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
    ]
