# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
