# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_configuration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_log',
            name='status',
            field=models.TextField(default=b'success'),
        ),
    ]
