# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_activity_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
