# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20160519_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='id',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
