# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 09:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20160520_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
